### ISSUE TITLE
New loading indicator

### ISSUE THREAD

**Issue by prajwalkulkarni** [hane-smitter/react-loading-indicator#1]
I'd want to work on adding a new loading indicator that consists of 4 small squares that are rotated about 45 deg about the x-axis. These individual squares move to and fro on their x-axis and rotate 90deg about their pivot point.
Could you kindly assign me this under the `hacktober-accepted` label?

**Comment by hane-smitter** [comment]
As you wish, I have assigned you the task

**Comment by prajwalkulkarni** [comment]
I've created a PR, kindly check. Also, would you mind updating the label to, `hacktoberfest-accepted`?

**Comment by hane-smitter** [comment]
Hello, the loader is not quite customizable yet as a user of the library would want to tailor a loader further to suit his needs. Tip: Use em values that will ensure responsive size of the loader. Also default color should be "limegreen". Have a feature like: if a user provides color prop as a string, then the whole loader will be the color value of that string. If color prop is an array then the array of color will be distributed to individual boxes. like so

The loader is great. It is a worth inclusion just some fixes to be done

**Comment by prajwalkulkarni** [comment]
Done, I've applied the suggested changes and updated the PR, kindly review. Also, could you kindly add the `hacktoberfest-accepted` label to the PR so that it is considered under hacktoberfest contest? Thanks.

**Comment by hane-smitter** [comment]
Fixed, you can npm install to test your loading indicators now
